name: cardexam
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dio: ^4.0.6
  dropdown_button2: ^1.9.2
  shimmer: ^2.0.0
  flutter_secure_storage: ^7.0.1
  hive: ^2.2.3
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5
  flutter_keyboard_size: ^1.0.1
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans.ttf